### PR TITLE
Fix platform_windows broken since #190 extern "C" fix for platform_unix

### PR DESCRIPTION
**Pull request by gavinbeatty**
win32_log and win32_log_args were not declared extern "C"
even though they were defined extern "C".

Without the fix, build.bat has the following errors:

```
src\platform_windows.cc(372): error C2732: linkage specification contradicts earlier specification for 'win32_log'
src\platform_windows.cc(371): note: see declaration of 'win32_log'
src\platform_windows.cc(383): error C2732: linkage specification contradicts earlier specification for 'win32_log_args'
src\platform_windows.cc(382): note: see declaration of 'win32_log_args'
```

Apologies, this was introduced by me when fixing Linux builds in #190.

### CODE REVIEW

**Comment by serge-rgb** [comment]
Thanks for the fix!
