### ISSUE TITLE
Doesn't build on Ubuntu 18.10

### ISSUE THREAD

**Issue by prokoudine** [serge-rgb/milton#111]
I know you don't support Linux, but thought I'd report anyway. I'm sorry if I'm wasting your time.

```
[ 80%] Building CXX object CMakeFiles/Milton.dir/src/unity.cc.o
In file included from /home/alex/soft/graphics/milton/milton-2019-03-17/src/common.h:8,
                 from /home/alex/soft/graphics/milton/milton-2019-03-17/src/vector.h:7,
                 from /home/alex/soft/graphics/milton/milton-2019-03-17/src/utils.h:7,
                 from /home/alex/soft/graphics/milton/milton-2019-03-17/src/stroke.h:6,
                 from /home/alex/soft/graphics/milton/milton-2019-03-17/src/StrokeList.h:12,
                 from /home/alex/soft/graphics/milton/milton-2019-03-17/src/StrokeList.cc:4,
                 from /home/alex/soft/graphics/milton/milton-2019-03-17/src/unity.cc:4:
/home/alex/soft/graphics/milton/milton-2019-03-17/src/milton_configuration.h:10: warning: "MILTON_DEBUG" redefined
 #define MILTON_DEBUG 1
 
<command-line>: note: this is the location of the previous definition
/home/alex/soft/graphics/milton/milton-2019-03-17/src/unity.cc:32:17: fatal error: platform_main_unix.cc: No such file or directory
        #include "platform_main_unix.cc"
                 ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
